package io.delta.flink.source;

import io.delta.flink.source.internal.builder.BoundedDeltaSourceBuilder;
import io.delta.flink.source.internal.builder.DeltaBulkFormat;
import org.apache.flink.core.fs.Path;
import org.apache.flink.table.data.RowData;
import org.apache.hadoop.conf.Configuration;

public class RowDataBoundedDeltaSourceBuilder
    extends BoundedDeltaSourceBuilder<RowData, RowDataBoundedDeltaSourceBuilder> {

    RowDataBoundedDeltaSourceBuilder(
        Path tablePath,
        DeltaBulkFormat<RowData> bulkFormat,
        Configuration hadoopConfiguration) {
        super(tablePath, bulkFormat, hadoopConfiguration);
    }

    //////////////////////////////////////////////////////////
    ///     We have to override methods from base class    ///
    /// to include them in javadoc generated by sbt-unidoc ///
    //////////////////////////////////////////////////////////
    @Override
    public RowDataBoundedDeltaSourceBuilder versionAsOf(long snapshotVersion) {
        return super.versionAsOf(snapshotVersion);
    }

    @Override
    public RowDataBoundedDeltaSourceBuilder timestampAsOf(String snapshotTimestamp) {
        return super.timestampAsOf(snapshotTimestamp);
    }

    @Override
    public RowDataBoundedDeltaSourceBuilder option(String optionName, String optionValue) {
        return super.option(optionName, optionValue);
    }

    @Override
    public RowDataBoundedDeltaSourceBuilder option(String optionName, boolean optionValue) {
        return super.option(optionName, optionValue);
    }

    @Override
    public RowDataBoundedDeltaSourceBuilder option(String optionName, int optionValue) {
        return super.option(optionName, optionValue);
    }

    @Override
    public RowDataBoundedDeltaSourceBuilder option(String optionName, long optionValue) {
        return super.option(optionName, optionValue);
    }

    @Override
    @SuppressWarnings("unchecked")
    public DeltaSource<RowData> build() {
        validateMandatoryOptions();
        validateOptionExclusions();

        return new DeltaSource<>(
            tablePath,
            bulkFormat,
            DEFAULT_BOUNDED_SPLIT_ENUMERATOR_PROVIDER,
            hadoopConfiguration,
            sourceConfiguration
        );
    }
}
